name: Trigger Jenkins Pipeline
inputs:
  JENKINS_URL:
    description: URL to Jenkins job that you want to trigger
    type: string
    required: true
  JENKINS_USER:
    description: User to authorize request to Jenkins API
    type: string
    required: true
  JENKINS_API_KEY:
    description: User's API key
    type: string
    required: true
runs:
  using: composite
  steps:
    - run: |
        cd ${{ github.action_path }}
        ./trigger.sh ${{ inputs.JENKINS_USER }} ${{ inputs.JENKINS_API_KEY }} ${{ inputs.JENKINS_URL }} 
      shell: bash
branding:
  icon: wind
  color: green
